title: Mitchell R. Vollger
email: mvollger@uw.edu
description: >- # this means to ignore newlines until "baseurl:"
  Doctoral candidate in Evan E. Eichler's lab.
  
twitter_username: mrvollger
github_username: mrvollger
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zo

include:
  - _pages

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Mitchell R. Vollger"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Doctoral candidate in Evan E. Eichler's lab."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mrvollger.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrvollger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrvollger"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8651-1615"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=oocozW4AAAAJ&hl"



footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrvollger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrvollger"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


