title: Mitchell R. Vollger, Ph.D.
email: mrvollger@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Postdoctoral fellow in Evan E. Eichler's lab.
  
twitter_username: mrvollger
github_username: mrvollger
minimal_mistakes_skin:  "contrast"
#"dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zo
date_format: "%Y-%m-%d"

include:
  - _pages

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Mitchell R. Vollger"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Postdoctoral fellow"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mrvollger.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrvollger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrvollger"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8651-1615"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-scroll"
      url: "https://scholar.google.com/citations?user=oocozW4AAAAJ&hl"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:mrvollger@gmail.com

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/mrvollger"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrvollger"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrvollger"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8651-1615"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-scroll"
      url: "https://scholar.google.com/citations?user=oocozW4AAAAJ&hl"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:mrvollger@gmail.com


# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-JR195G0SX3"
    anonymize_ip: false # default


# twitter feed? 
twitter:
  username: "mrvollger"